package su.bathroom.registry;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class BathroomAnimations {
    public static final Animation MUSHLET_SQUASH = Animation.Builder.create(1.5f).looping().addBoneAnimation("bone", new Transformation(Transformation.Targets.TRANSLATE, new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f), Transformation.Interpolations.LINEAR), new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, -2f, 0f), Transformation.Interpolations.LINEAR), new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 2f, 0f), Transformation.Interpolations.LINEAR), new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f), Transformation.Interpolations.LINEAR))).addBoneAnimation("bone2", new Transformation(Transformation.Targets.TRANSLATE, new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f), Transformation.Interpolations.LINEAR))).addBoneAnimation("bone2", new Transformation(Transformation.Targets.SCALE, new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f), Transformation.Interpolations.LINEAR), new Keyframe(0.5f, AnimationHelper.createScalingVector(1.2f, 1f, 1.2f), Transformation.Interpolations.LINEAR), new Keyframe(1f, AnimationHelper.createScalingVector(0.8f, 1f, 0.8f), Transformation.Interpolations.LINEAR), new Keyframe(1.5f, AnimationHelper.createScalingVector(1f, 1f, 1f), Transformation.Interpolations.LINEAR))).addBoneAnimation("bone3", new Transformation(Transformation.Targets.TRANSLATE, new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f), Transformation.Interpolations.LINEAR), new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, -1f, 0f), Transformation.Interpolations.LINEAR), new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 1f, 0f), Transformation.Interpolations.LINEAR), new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f), Transformation.Interpolations.LINEAR))).build();
}
